# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_text', '0002_input_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='input_text',
            name='text_word',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='input_text',
            name='text',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
