# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_text', '0003_auto_20170222_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input_word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_word', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='input_text',
            name='text_word',
        ),
    ]
