# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read_text', '0004_auto_20170222_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count_word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('id_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read_text.Word')),
            ],
        ),
    ]
